In [2]:
import pandas as pd
import sqlite3

In [3]:
df = pd.read_excel("data/g13_ridesharing.xlsx")
conn = sqlite3.connect("data/g13_ridesharing.db")

In [5]:
cars = df.loc[:, ['id_car', 'description', 'id_company', 'car_type']].copy()
cars = cars.drop_duplicates(subset='id_car', keep='first')
cars['id_car'] = cars['id_car'].astype(int)
cars['id_company'] = cars['id_company'].astype(int)
cars['car_type'] = cars['car_type'].astype(int)
cars = cars.rename(columns={'id_car': 'id'})

In [6]:
cars.to_sql("Car", conn, if_exists="append", index=False)

1199

In [7]:
pd.read_sql("SELECT * FROM Car LIMIT 20", conn)

    id  description  id_company  car_type
0    1        trade         347         1
1    2        force          60         1
2    3      subject         307         1
3    4         most         373         1
4    5      serious          68         1
5    6         hand         156         1
6    7      current         413         1
7    8  traditional         415         1
8    9        after         429         1
9   10         full         461         1
10  11     indicate          68         1
11  12          yes         220         1
12  13         lose         329         1
13  14    interview         484         1
14  15    direction         301         1
15  16      machine         301         1
16  17      against          95         1
17  18     customer         436         1
18  19        heavy         424         1
19  20      company         165         1

In [8]:
companies = df.loc[:, ['id_company', 'name', 'begin_date']].copy()
companies = companies.drop_duplicates(subset='id_company', keep='first')
companies['id_company'] = companies['id_company'].astype(int)
companies = companies.rename(columns={'id_company': 'id'})

In [9]:
companies.to_sql("Company", conn, if_exists="append", index=False)

500

In [10]:
pd.read_sql("SELECT * FROM Company LIMIT 20", conn)

    id                            name  begin_date
0    1                   Roberts-Hurst  25/12/2025
1    2       Brewer, Gregory and Kelly  15/05/2022
2    3       Pugh, Harrison and Martin  02/03/2023
3    4                   Roberts-Hicks  22/01/2025
4    5         Hahn, Allen and Lambert  07/10/2023
5    6                   Clark-Spencer  22/08/2022
6    7     Miller, Gutierrez and Stark  23/12/2022
7    8  Bradshaw, Strickland and Olson  08/05/2024
8    9                Marquez-Gonzalez  22/05/2023
9   10                 Nguyen-Williams  21/07/2024
10  11               Martinez-Thompson  03/05/2024
11  12                  Holloway-Smith  11/11/2021
12  13                   Robinson-Kemp  23/11/2024
13  14       Romero, Johnson and Lopez  18/01/2023
14  15              Williamson-Gilbert  12/02/2022
15  16                   Mayo and Sons  09/03/2022
16  17                   Norton-Watson  13/03/2021
17  18                     Escobar LLC  22/12/2024
18  19    Gutierrez, Johnson and Jones  29/03/2023
19  20                     Massey-Pace  18/02/2022

In [11]:
contracts = df.loc[:, ['id_contract', 'contract_start', 'contract_end', 'id_company', 'id_driver']].copy()
contracts = contracts.drop_duplicates(subset='id_contract', keep='first')
contracts['id_contract'] = contracts['id_contract'].astype(int)
contracts['id_company'] = contracts['id_company'].astype(int)
contracts['id_driver'] = contracts['id_driver'].astype(int)
contracts = contracts.rename(columns={'id_contract': 'id'})

In [12]:
contracts.to_sql("Contract", conn, if_exists="append", index=False)

9907

In [13]:
pd.read_sql("SELECT * FROM Contract LIMIT 20", conn)

    id       contract_start         contract_end  id_company  id_driver
0    1  06/10/2024 15:47:00                 None         403        762
1    2  25/04/2024 15:05:00  21/08/2026 15:05:00         348        312
2    3  04/10/2024 08:18:00  21/05/2025 08:18:00         423        641
3    4  27/01/2025 12:25:00                 None         205        444
4    5  30/08/2024 20:07:00                 None          81        789
5    6  26/11/2021 12:23:00  03/11/2024 12:23:00          85        537
6    7  31/03/2025 07:07:00                 None         149        956
7    8  27/01/2025 20:37:00  31/08/2025 20:37:00         205        698
8    9  14/02/2022 13:21:00  21/11/2023 13:21:00          34        771
9   10  14/07/2024 08:00:00  29/11/2025 08:00:00         407        261
10  11  08/01/2023 11:28:00                 None          88        943
11  12  12/04/2022 07:11:00                 None         320        192
12  13  06/04/2022 12:18:00                 None         207        723
13  14  07/05/2025 20:31:00                 None         347        551
14  15  13/05/2024 08:56:00  21/11/2026 08:56:00         359        903
15  16  11/05/2023 17:22:00  07/05/2024 17:22:00         383        610
16  17  10/12/2021 17:36:00                 None         322        441
17  18  19/12/2024 10:37:00                 None         362        114
18  19  15/05/2021 10:58:00                 None         282        340
19  20  12/10/2023 08:47:00                 None         315        826

In [14]:
customers = df.loc[:, ['id_customer', 'name_customer', 'email', 'phone', 'date_of_birth']].copy()
customers = customers.drop_duplicates(subset='id_customer', keep='first')
customers['id_customer'] = customers['id_customer'].astype(int)
customers['phone'] = customers['phone'].astype(int)
customers = customers.rename(columns={'id_customer': 'id'})
customers = customers.rename(columns={'name_customer': 'name'})

In [15]:
customers.to_sql("Customer", conn, if_exists="append", index=False)

40

In [16]:
pd.read_sql("SELECT * FROM Customer LIMIT 20", conn)

,id,name,email,phone,date_of_birth
0,1,Ana Costa,ana.costa896@gmail.com,900382935,25/09/1988
1,2,Ana Ferreira,ana.ferreira244@outlook.com,900077394,13/01/1978
2,3,Ana Pereira,ana.pereira86@outlook.com,900382454,11/07/1971
3,4,Ana Santos,ana.santos181@outlook.com,900095407,02/12/1999
4,5,Ana Silva,ana.silva192@gmail.com,900073015,09/02/1977
5,6,Goncalo Costa,goncalo.costa154@gmail.com,900049867,20/06/1996
6,7,Goncalo Ferreira,goncalo.ferreira385@gmail.com,900236832,20/08/1991
7,8,Goncalo Pereira,goncalo.pereira109@icloud.com,900168951,02/07/1971
8,9,Goncalo Santos,goncalo.santos239@gmail.com,900892644,10/11/1979
9,10,Goncalo Silva,goncalo.silva465@icloud.com,900133976,21/10/1994
10,11,Ines Costa,ines.costa852@icloud.com,900509648,20/10/2010
11,12,Ines Ferreira,ines.ferreira114@gmail.com,900044296,13/05/1989
12,13,Ines Pereira,ines.pereira158@icloud.com,900252235,17/02/1974
13,14,Ines Santos,ines.santos161@icloud.com,900182383,31/10/1980
14,15,Ines Silva,ines.silva102@gmail.com,900358102,14/12/1990
15,16,Joao Costa,joao.costa16@gmail.com,900181252,21/10/1995
16,17,Joao Ferreira,joao.ferreira201@gmail.com,900034900,13/07/1993
17,18,Joao Pereira,joao.pereira271@outlook.com,900364993,06/09/1986
18,19,Joao Santos,joao.santos10@icloud.com,900406029,14/10/1980
19,20,Joao Silva,joao.silva196@icloud.com,900106759,25/01/1980

In [17]:
drivers = df.loc[:, ['id_driver', 'nickname', 'driver_type', 'ratings']].copy()
drivers = drivers.drop_duplicates(subset='id_driver', keep='first')
drivers['id_driver'] = drivers['id_driver'].astype(int)
drivers = drivers.rename(columns={'id_driver': 'id'})

In [18]:
drivers.to_sql("Driver", conn, if_exists="append", index=False)

OperationalError: table Driver has no column named ratings

In [ ]:
pd.read_sql("SELECT * FROM Driver LIMIT 20", conn)

In [22]:
rides = df.loc[:, ['id_ride', 'id_company', 'id_driver', 'id_customer', 'id_car', 'origin', 'destination', 'ride_date']].copy()
rides = rides.drop_duplicates(subset='id_ride', keep='first')
rides['id_ride'] = rides['id_ride'].astype(int)
rides['id_company'] = rides['id_company'].astype(int)
rides['id_driver'] = rides['id_driver'].astype(int)
rides['id_customer'] = rides['id_customer'].astype(int)
rides['id_car'] = rides['id_car'].astype(int)
rides = rides.rename(columns={'id_ride': 'id'})

In [23]:
rides.to_sql("Ride", conn, if_exists="append", index=False)

10827

In [24]:
pd.read_sql("SELECT * FROM Ride LIMIT 20", conn)

,id,id_company,id_driver,id_customer,id_car,origin,destination,ride_date
0,1,403,762,1,1199,"R. Dr. Roberto Frias, Porto, Portugal","Vila Real, Portugal",14/11/2024
1,2,348,312,1,1198,"Rua Augusta, Lisbon, Portugal","R. de Santa Catarina, Porto, Portugal",31/05/2024
2,3,423,641,1,1197,"Rua Augusta, Lisbon, Portugal","Guimarães, Portugal",24/11/2024
3,4,205,444,1,155,"Braga, Portugal","Vila Real, Portugal",01/03/2025
4,5,81,789,1,1196,"Faro, Portugal","Vila Real, Portugal",22/11/2024
5,6,85,537,1,87,"Guimarães, Portugal","Rua de Fernandes Tomás, Porto, Portugal",02/05/2022
6,7,149,956,1,1195,"Faro, Portugal","Coimbra, Portugal",27/07/2025
7,8,205,698,1,155,"R. de Santa Catarina, Porto, Portugal","Vila Real, Portugal",07/04/2025
8,9,34,771,1,136,"Aveiro, Portugal","Rua de Fernandes Tomás, Porto, Portugal",04/01/2025
9,10,407,261,1,1194,"Guimarães, Portugal","R. de Santa Catarina, Porto, Portugal",13/08/2024
10,11,88,943,1,1193,"Guimarães, Portugal","Aveiro, Portugal",18/10/2023
11,12,320,192,1,1192,"Praça do Comércio, Lisbon, Portugal","Aveiro, Portugal",16/05/2022
12,13,207,723,1,1191,"Praça do Comércio, Lisbon, Portugal","R. Dr. Roberto Frias, Porto, Portugal",19/06/2022
13,14,347,551,1,1,"Aveiro, Portugal","Rua Augusta, Lisbon, Portugal",29/07/2025
14,15,359,903,1,97,"R. Dr. Roberto Frias, Porto, Portugal","Rua Augusta, Lisbon, Portugal",16/06/2024
15,16,383,610,1,126,"Coimbra, Portugal","Aveiro, Portugal",20/06/2024
16,17,322,441,1,1190,"Aveiro, Portugal","R. de Santa Catarina, Porto, Portugal",08/09/2025
17,18,362,114,1,1189,"Rua de Santo António, Braga, Portugal","Porto, Portugal",24/03/2025
18,19,282,340,1,1188,"Guimarães, Portugal","Av. da Boavista, Porto, Portugal",11/04/2025
19,20,315,826,1,1187,"Praça do Comércio, Lisbon, Portugal","Rua de Santo António, Braga, Portugal",02/12/2023

In [4]:
#testar codigo de novo; eliminar colunas da base de dados
cur = conn.cursor()
cur.execute("DELETE FROM Car;")
cur.execute("DELETE FROM Company;")
cur.execute("DELETE FROM Contract;")
cur.execute("DELETE FROM Customer;")

cur.execute("DELETE FROM Driver;")
cur.execute("DELETE FROM Ride;")
conn.commit()

In [25]:
conn.close()